vich_uploader:
  db_driver: orm

  mappings:
    user_image:
      uri_prefix: '%app.path.users_images%'
      upload_destination: '%kernel.project_dir%/public%app.path.users_images%'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    articles_image:
      uri_prefix: '%app.path.articles_images%'
      upload_destination: '%kernel.project_dir%/public%app.path.articles_images%'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
